/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateCabinetProductInput = {
  id?: string | null,
  wSKU: string,
  vSKU: string,
  brand: string,
  doorStyle: string,
  discount?: number | null,
  costFactor?: number | null,
  assemblyFee?: number | null,
  assemblyCost?: number | null,
  retailPrice?: number | null,
  discountPrice?: number | null,
  discountFactor?: number | null,
  name?: string | null,
  height?: number | null,
  width?: number | null,
  weight?: number | null,
  doors?: string | null,
  drawers?: string | null,
  shelves?: string | null,
  species?: string | null,
  shippingClass?: string | null,
  imagePath?: string | null,
  categories?: string | null,
  tags?: string | null,
  publish?: boolean | null,
};

export type ModelCabinetProductConditionInput = {
  wSKU?: ModelStringInput | null,
  vSKU?: ModelStringInput | null,
  brand?: ModelStringInput | null,
  doorStyle?: ModelStringInput | null,
  discount?: ModelFloatInput | null,
  costFactor?: ModelFloatInput | null,
  assemblyFee?: ModelFloatInput | null,
  assemblyCost?: ModelFloatInput | null,
  retailPrice?: ModelFloatInput | null,
  discountPrice?: ModelFloatInput | null,
  discountFactor?: ModelFloatInput | null,
  name?: ModelStringInput | null,
  height?: ModelFloatInput | null,
  width?: ModelFloatInput | null,
  weight?: ModelFloatInput | null,
  doors?: ModelStringInput | null,
  drawers?: ModelStringInput | null,
  shelves?: ModelStringInput | null,
  species?: ModelStringInput | null,
  shippingClass?: ModelStringInput | null,
  imagePath?: ModelStringInput | null,
  categories?: ModelStringInput | null,
  tags?: ModelStringInput | null,
  publish?: ModelBooleanInput | null,
  and?: Array< ModelCabinetProductConditionInput | null > | null,
  or?: Array< ModelCabinetProductConditionInput | null > | null,
  not?: ModelCabinetProductConditionInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type CabinetProduct = {
  __typename: "CabinetProduct",
  id: string,
  wSKU: string,
  vSKU: string,
  brand: string,
  doorStyle: string,
  discount?: number | null,
  costFactor?: number | null,
  assemblyFee?: number | null,
  assemblyCost?: number | null,
  retailPrice?: number | null,
  discountPrice?: number | null,
  discountFactor?: number | null,
  name?: string | null,
  height?: number | null,
  width?: number | null,
  weight?: number | null,
  doors?: string | null,
  drawers?: string | null,
  shelves?: string | null,
  species?: string | null,
  shippingClass?: string | null,
  imagePath?: string | null,
  categories?: string | null,
  tags?: string | null,
  publish?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type UpdateCabinetProductInput = {
  id: string,
  wSKU?: string | null,
  vSKU?: string | null,
  brand?: string | null,
  doorStyle?: string | null,
  discount?: number | null,
  costFactor?: number | null,
  assemblyFee?: number | null,
  assemblyCost?: number | null,
  retailPrice?: number | null,
  discountPrice?: number | null,
  discountFactor?: number | null,
  name?: string | null,
  height?: number | null,
  width?: number | null,
  weight?: number | null,
  doors?: string | null,
  drawers?: string | null,
  shelves?: string | null,
  species?: string | null,
  shippingClass?: string | null,
  imagePath?: string | null,
  categories?: string | null,
  tags?: string | null,
  publish?: boolean | null,
};

export type DeleteCabinetProductInput = {
  id: string,
};

export type ModelCabinetProductFilterInput = {
  id?: ModelIDInput | null,
  wSKU?: ModelStringInput | null,
  vSKU?: ModelStringInput | null,
  brand?: ModelStringInput | null,
  doorStyle?: ModelStringInput | null,
  discount?: ModelFloatInput | null,
  costFactor?: ModelFloatInput | null,
  assemblyFee?: ModelFloatInput | null,
  assemblyCost?: ModelFloatInput | null,
  retailPrice?: ModelFloatInput | null,
  discountPrice?: ModelFloatInput | null,
  discountFactor?: ModelFloatInput | null,
  name?: ModelStringInput | null,
  height?: ModelFloatInput | null,
  width?: ModelFloatInput | null,
  weight?: ModelFloatInput | null,
  doors?: ModelStringInput | null,
  drawers?: ModelStringInput | null,
  shelves?: ModelStringInput | null,
  species?: ModelStringInput | null,
  shippingClass?: ModelStringInput | null,
  imagePath?: ModelStringInput | null,
  categories?: ModelStringInput | null,
  tags?: ModelStringInput | null,
  publish?: ModelBooleanInput | null,
  createdAt?: ModelStringInput | null,
  updatedAt?: ModelStringInput | null,
  and?: Array< ModelCabinetProductFilterInput | null > | null,
  or?: Array< ModelCabinetProductFilterInput | null > | null,
  not?: ModelCabinetProductFilterInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type ModelCabinetProductConnection = {
  __typename: "ModelCabinetProductConnection",
  items:  Array<CabinetProduct | null >,
  nextToken?: string | null,
};

export enum ModelSortDirection {
  ASC = "ASC",
  DESC = "DESC",
}


export type ModelStringKeyConditionInput = {
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
};

export type ModelSubscriptionCabinetProductFilterInput = {
  id?: ModelSubscriptionIDInput | null,
  wSKU?: ModelSubscriptionStringInput | null,
  vSKU?: ModelSubscriptionStringInput | null,
  brand?: ModelSubscriptionStringInput | null,
  doorStyle?: ModelSubscriptionStringInput | null,
  discount?: ModelSubscriptionFloatInput | null,
  costFactor?: ModelSubscriptionFloatInput | null,
  assemblyFee?: ModelSubscriptionFloatInput | null,
  assemblyCost?: ModelSubscriptionFloatInput | null,
  retailPrice?: ModelSubscriptionFloatInput | null,
  discountPrice?: ModelSubscriptionFloatInput | null,
  discountFactor?: ModelSubscriptionFloatInput | null,
  name?: ModelSubscriptionStringInput | null,
  height?: ModelSubscriptionFloatInput | null,
  width?: ModelSubscriptionFloatInput | null,
  weight?: ModelSubscriptionFloatInput | null,
  doors?: ModelSubscriptionStringInput | null,
  drawers?: ModelSubscriptionStringInput | null,
  shelves?: ModelSubscriptionStringInput | null,
  species?: ModelSubscriptionStringInput | null,
  shippingClass?: ModelSubscriptionStringInput | null,
  imagePath?: ModelSubscriptionStringInput | null,
  categories?: ModelSubscriptionStringInput | null,
  tags?: ModelSubscriptionStringInput | null,
  publish?: ModelSubscriptionBooleanInput | null,
  createdAt?: ModelSubscriptionStringInput | null,
  updatedAt?: ModelSubscriptionStringInput | null,
  and?: Array< ModelSubscriptionCabinetProductFilterInput | null > | null,
  or?: Array< ModelSubscriptionCabinetProductFilterInput | null > | null,
};

export type ModelSubscriptionIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  in?: Array< string | null > | null,
  notIn?: Array< string | null > | null,
};

export type ModelSubscriptionFloatInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  in?: Array< number | null > | null,
  notIn?: Array< number | null > | null,
};

export type ModelSubscriptionBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
};

export type CreateCabinetProductMutationVariables = {
  input: CreateCabinetProductInput,
  condition?: ModelCabinetProductConditionInput | null,
};

export type CreateCabinetProductMutation = {
  createCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateCabinetProductMutationVariables = {
  input: UpdateCabinetProductInput,
  condition?: ModelCabinetProductConditionInput | null,
};

export type UpdateCabinetProductMutation = {
  updateCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteCabinetProductMutationVariables = {
  input: DeleteCabinetProductInput,
  condition?: ModelCabinetProductConditionInput | null,
};

export type DeleteCabinetProductMutation = {
  deleteCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetCabinetProductQueryVariables = {
  id: string,
};

export type GetCabinetProductQuery = {
  getCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListCabinetProductsQueryVariables = {
  filter?: ModelCabinetProductFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCabinetProductsQuery = {
  listCabinetProducts?:  {
    __typename: "ModelCabinetProductConnection",
    items:  Array< {
      __typename: "CabinetProduct",
      id: string,
      wSKU: string,
      vSKU: string,
      brand: string,
      doorStyle: string,
      discount?: number | null,
      costFactor?: number | null,
      assemblyFee?: number | null,
      assemblyCost?: number | null,
      retailPrice?: number | null,
      discountPrice?: number | null,
      discountFactor?: number | null,
      name?: string | null,
      height?: number | null,
      width?: number | null,
      weight?: number | null,
      doors?: string | null,
      drawers?: string | null,
      shelves?: string | null,
      species?: string | null,
      shippingClass?: string | null,
      imagePath?: string | null,
      categories?: string | null,
      tags?: string | null,
      publish?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListCabinetProductBywSkuQueryVariables = {
  wSKU: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCabinetProductFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCabinetProductBywSkuQuery = {
  listCabinetProductBywSku?:  {
    __typename: "ModelCabinetProductConnection",
    items:  Array< {
      __typename: "CabinetProduct",
      id: string,
      wSKU: string,
      vSKU: string,
      brand: string,
      doorStyle: string,
      discount?: number | null,
      costFactor?: number | null,
      assemblyFee?: number | null,
      assemblyCost?: number | null,
      retailPrice?: number | null,
      discountPrice?: number | null,
      discountFactor?: number | null,
      name?: string | null,
      height?: number | null,
      width?: number | null,
      weight?: number | null,
      doors?: string | null,
      drawers?: string | null,
      shelves?: string | null,
      species?: string | null,
      shippingClass?: string | null,
      imagePath?: string | null,
      categories?: string | null,
      tags?: string | null,
      publish?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListCabinetProductByvSkuQueryVariables = {
  vSKU: string,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCabinetProductFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCabinetProductByvSkuQuery = {
  listCabinetProductByvSku?:  {
    __typename: "ModelCabinetProductConnection",
    items:  Array< {
      __typename: "CabinetProduct",
      id: string,
      wSKU: string,
      vSKU: string,
      brand: string,
      doorStyle: string,
      discount?: number | null,
      costFactor?: number | null,
      assemblyFee?: number | null,
      assemblyCost?: number | null,
      retailPrice?: number | null,
      discountPrice?: number | null,
      discountFactor?: number | null,
      name?: string | null,
      height?: number | null,
      width?: number | null,
      weight?: number | null,
      doors?: string | null,
      drawers?: string | null,
      shelves?: string | null,
      species?: string | null,
      shippingClass?: string | null,
      imagePath?: string | null,
      categories?: string | null,
      tags?: string | null,
      publish?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type ListCabinetProductByBrandAndDoorStyleQueryVariables = {
  brand: string,
  doorStyle?: ModelStringKeyConditionInput | null,
  sortDirection?: ModelSortDirection | null,
  filter?: ModelCabinetProductFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCabinetProductByBrandAndDoorStyleQuery = {
  listCabinetProductByBrandAndDoorStyle?:  {
    __typename: "ModelCabinetProductConnection",
    items:  Array< {
      __typename: "CabinetProduct",
      id: string,
      wSKU: string,
      vSKU: string,
      brand: string,
      doorStyle: string,
      discount?: number | null,
      costFactor?: number | null,
      assemblyFee?: number | null,
      assemblyCost?: number | null,
      retailPrice?: number | null,
      discountPrice?: number | null,
      discountFactor?: number | null,
      name?: string | null,
      height?: number | null,
      width?: number | null,
      weight?: number | null,
      doors?: string | null,
      drawers?: string | null,
      shelves?: string | null,
      species?: string | null,
      shippingClass?: string | null,
      imagePath?: string | null,
      categories?: string | null,
      tags?: string | null,
      publish?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateCabinetProductSubscriptionVariables = {
  filter?: ModelSubscriptionCabinetProductFilterInput | null,
};

export type OnCreateCabinetProductSubscription = {
  onCreateCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateCabinetProductSubscriptionVariables = {
  filter?: ModelSubscriptionCabinetProductFilterInput | null,
};

export type OnUpdateCabinetProductSubscription = {
  onUpdateCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteCabinetProductSubscriptionVariables = {
  filter?: ModelSubscriptionCabinetProductFilterInput | null,
};

export type OnDeleteCabinetProductSubscription = {
  onDeleteCabinetProduct?:  {
    __typename: "CabinetProduct",
    id: string,
    wSKU: string,
    vSKU: string,
    brand: string,
    doorStyle: string,
    discount?: number | null,
    costFactor?: number | null,
    assemblyFee?: number | null,
    assemblyCost?: number | null,
    retailPrice?: number | null,
    discountPrice?: number | null,
    discountFactor?: number | null,
    name?: string | null,
    height?: number | null,
    width?: number | null,
    weight?: number | null,
    doors?: string | null,
    drawers?: string | null,
    shelves?: string | null,
    species?: string | null,
    shippingClass?: string | null,
    imagePath?: string | null,
    categories?: string | null,
    tags?: string | null,
    publish?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
